name: website
description: A personal website
publish_to: 'none' 
version: 0.1.0


environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  beamer: ^1.5.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1 

flutter:

  uses-material-design: true
